const $ = s => document.querySelector(s);
const esc = value => String(value ?? "").replace(/[&<>\"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const asset = src => src ? `/asset?path=${encodeURIComponent(src)}` : "";
let data, projectIndex = 0, selected = null, insertAt = null, dirty = false, uploadTarget = null;
const defaults = {
  heading: {type:"heading",heading:"New heading"}, text:{type:"text",text:"Write your story here."},
  image:{type:"image",src:"",alt:"",caption:"",size:"normal"}, video:{type:"video",src:"",caption:"",size:"wide"},
  split:{type:"split",heading:"Section heading",text:"Add text that supports this image.",src:"",alt:"",side:"left"}, divider:{type:"divider"}
};
function project(){ return data.projects[projectIndex]; }
function markDirty(){ dirty=true; $("#status").textContent="Unsaved changes"; $("#status").className="toast"; }
function paragraphs(text){ return String(text||"").split(/\n\n+/).map(p=>`<p>${esc(p)}</p>`).join(""); }
function blockHTML(block){
  if(block.type==="heading") return `<h2 class="story-heading">${esc(block.heading)}</h2>`;
  if(block.type==="text") return `<div class="story-text">${paragraphs(block.text)}</div>`;
  if(block.type==="divider") return `<hr class="story-divider">`;
  if(block.type==="image") return `<figure class="story-media ${block.size||"normal"}">${block.src?`<img src="${asset(block.src)}" alt="${esc(block.alt)}">`:`<div class="empty-blocks">Choose an image in the panel</div>`}${block.caption?`<figcaption>${esc(block.caption)}</figcaption>`:""}</figure>`;
  if(block.type==="video") return `<figure class="story-media ${block.size||"wide"}">${block.src?`<video src="${asset(block.src)}" controls></video>`:`<div class="empty-blocks">Choose a video in the panel</div>`}${block.caption?`<figcaption>${esc(block.caption)}</figcaption>`:""}</figure>`;
  if(block.type==="split") return `<section class="story-split ${block.side||"left"}"><div class="split-media">${block.src?`<img src="${asset(block.src)}" alt="${esc(block.alt)}">`:`<div class="empty-blocks">Choose an image</div>`}</div><div><h2>${esc(block.heading)}</h2>${paragraphs(block.text)}</div></section>`;
  return "";
}
function insertRow(index){ return `<div class="insert-row" data-insert="${index}"><button class="insert-button ${insertAt===index?"open":""}">＋</button>${insertAt===index?`<div class="add-menu">${Object.keys(defaults).map(t=>`<button data-add="${t}">${t==="split"?"Image + text":t[0].toUpperCase()+t.slice(1)}</button>`).join("")}</div>`:""}</div>`; }
function headerOptions(p){return Object.assign({showMeta:true,showTitle:true,showSummary:true,showTags:true,showDivider:false},p.header||{})}
function renderCanvas(){
  const p=project(), blocks=p.blocks||[], header=headerOptions(p); $("#openPage").href=`http://localhost:3000/projects/${p.category.toLowerCase()}/${p.slug}`;
  $("#canvas").innerHTML=`<div class="preview-nav"><span>← Projects</span><span>Peter Murphy</span></div><header class="preview-hero editable-header ${selected==="header"?"selected":""}" data-header><span class="header-edit-label">Click to edit header</span>${header.showMeta?`<div class="preview-kicker">${esc(p.category)} · ${esc(p.year)}</div>`:""}${header.showTitle?`<h1>${esc(p.title)}</h1>`:""}${header.showSummary?`<div class="preview-summary">${esc(p.summary)}</div>`:""}${header.showTags?`<div class="preview-tags">${(p.technologies||[]).map(x=>`<span>${esc(x)}</span>`).join("")}</div>`:""}</header>${header.showDivider?`<hr class="preview-header-divider">`:""}<div class="blocks">${insertRow(0)}${blocks.length?blocks.map((b,i)=>`<div class="block-shell ${selected===i?"selected":""}" data-block="${i}"><span class="block-actions">Click to edit</span>${blockHTML(b)}</div>${insertRow(i+1)}`).join(""):`<div class="empty-blocks">This page has no sections yet. Use + to add the first one.</div>`}</div>`;
  $("#canvas").querySelector("[data-header]").onclick=e=>{e.stopPropagation();selected="header";insertAt=null;renderAll(false)};
  $("#canvas").querySelectorAll("[data-block]").forEach(el=>el.onclick=e=>{e.stopPropagation();selected=+el.dataset.block;insertAt=null;renderAll(false)});
  $("#canvas").querySelectorAll(".insert-button").forEach(el=>el.onclick=e=>{e.stopPropagation();insertAt=+el.parentElement.dataset.insert;renderCanvas()});
  $("#canvas").querySelectorAll("[data-add]").forEach(el=>el.onclick=e=>{e.stopPropagation();const b=structuredClone(defaults[el.dataset.add]);project().blocks.splice(insertAt,0,b);selected=insertAt;insertAt=null;markDirty();renderAll(false)});
}
function field(label,key,value,type="input",extra=""){ return `<label class="field">${label}${type==="textarea"?`<textarea data-key="${key}" class="${extra}">${esc(value)}</textarea>`:type==="select"?`<select data-key="${key}">${extra.split("|").map(v=>`<option ${v===value?"selected":""}>${v}</option>`).join("")}</select>`:`<input data-key="${key}" value="${esc(value)}" ${extra}>`}</label>`; }
function categoryChoices(current){return [...new Set([...(data.categories||[]),current].filter(Boolean))].join("|")}
function projectInspector(){const p=project();return `<h2>Project settings</h2><p class="hint">The circular icon is used on project cards and the homepage, not as a large page image.</p><button class="media-button" id="chooseIcon">Choose circular project icon…</button>${p.image?`<img class="icon-preview" src="${asset(p.image)}" alt="">`:""}${field("Title","title",p.title)}${field("Short summary","summary",p.summary,"textarea","small-text")}${field("Category","category",p.category,"select",categoryChoices(p.category))}${field("Year","year",p.year)}${field("Tags — separate with commas","technologies",(p.technologies||[]).join(", "))}<label class="check"><input data-key="featured" type="checkbox" ${p.featured?"checked":""}> Featured project</label>`}
function headerInspector(){const p=project(),h=headerOptions(p);return `<h2>Page header</h2><p class="hint">Choose exactly what appears at the top of this project page.</p>${field("Title","title",p.title)}${field("Short summary","summary",p.summary,"textarea","small-text")}${field("Category","category",p.category,"select",categoryChoices(p.category))}${field("Year","year",p.year)}${field("Tags — separate with commas","technologies",(p.technologies||[]).join(", "))}<label class="check"><input data-header-key="showMeta" type="checkbox" ${h.showMeta?"checked":""}> Show category and year</label><label class="check"><input data-header-key="showTitle" type="checkbox" ${h.showTitle?"checked":""}> Show title</label><label class="check"><input data-header-key="showSummary" type="checkbox" ${h.showSummary?"checked":""}> Show summary</label><label class="check"><input data-header-key="showTags" type="checkbox" ${h.showTags?"checked":""}> Show tags</label><label class="check"><input data-header-key="showDivider" type="checkbox" ${h.showDivider?"checked":""}> Add compact divider below header</label><button class="media-button secondary" id="projectSettings">Project icon and settings</button>`}
function categoryInspector(){return `<h2>Project categories</h2><p class="hint">These become the filters across the Projects page. Renaming a category updates every project using it.</p><div class="category-list">${data.categories.map((name,index)=>`<div class="category-editor-row"><input data-category-index="${index}" value="${esc(name)}"><button data-category-up="${index}" title="Move up">↑</button><button data-category-down="${index}" title="Move down">↓</button><button class="danger" data-category-delete="${index}" title="Remove">×</button></div>`).join("")}</div><button class="media-button" id="addCategory">＋ Add category</button>`}
function blockInspector(b){let controls="";if(b.type==="heading")controls=field("Heading","heading",b.heading);if(b.type==="text")controls=field("Text","text",b.text,"textarea");if(["image","video","split"].includes(b.type))controls+=`<button class="media-button" id="chooseMedia">Choose ${b.type==="video"?"video":"image"}…</button>`;if(b.type==="image")controls+=field("Alt text","alt",b.alt)+field("Caption (optional)","caption",b.caption)+field("Width","size",b.size||"normal","select","normal|wide|full");if(b.type==="video")controls+=field("Caption (optional)","caption",b.caption)+field("Width","size",b.size||"wide","select","normal|wide|full");if(b.type==="split")controls+=field("Heading","heading",b.heading)+field("Text","text",b.text,"textarea")+field("Image side","side",b.side||"left","select","left|right")+field("Alt text","alt",b.alt);if(b.type==="divider")controls+=`<p class="hint">A quiet visual break between sections.</p>`;return `<h2>${b.type==="split"?"Image + text":b.type[0].toUpperCase()+b.type.slice(1)} section</h2><p class="hint">Changes appear on the page immediately.</p>${controls}<div class="inspector-actions"><button data-action="up">Move up</button><button data-action="down">Move down</button><button data-action="duplicate">Duplicate</button><button class="danger" data-action="delete">Delete</button></div>`}
function renderInspector(){
  const p=project(), isHeader=selected==="header", isCategories=selected==="categories", target=selected===null?p:isHeader?p.header??={}:isCategories?data.categories:p.blocks[selected];
  $("#inspector").innerHTML=isCategories?categoryInspector():selected===null?projectInspector():isHeader?headerInspector():blockInspector(target);
  if(isCategories){
    $("#inspector").querySelectorAll("[data-category-index]").forEach(el=>el.onchange=()=>{const index=+el.dataset.categoryIndex,old=data.categories[index],value=el.value.trim();if(!value){el.value=old;return}data.categories[index]=value;data.projects.forEach(item=>{if(item.category===old)item.category=value});markDirty();renderAll()});
    $("#inspector").querySelectorAll("[data-category-up]").forEach(el=>el.onclick=()=>moveCategory(+el.dataset.categoryUp,-1));
    $("#inspector").querySelectorAll("[data-category-down]").forEach(el=>el.onclick=()=>moveCategory(+el.dataset.categoryDown,1));
    $("#inspector").querySelectorAll("[data-category-delete]").forEach(el=>el.onclick=()=>deleteCategory(+el.dataset.categoryDelete));
    $("#addCategory").onclick=()=>{let name=prompt("New category name");name=name?.trim();if(!name||data.categories.includes(name))return;data.categories.push(name);markDirty();renderAll()};
    return;
  }
  $("#inspector").querySelectorAll("[data-key]").forEach(el=>{el.oninput=()=>{let v=el.type==="checkbox"?el.checked:el.value;if(el.dataset.key==="technologies")v=v.split(",").map(x=>x.trim()).filter(Boolean);p[el.dataset.key]=v;markDirty();renderCanvas();renderProjects()}});
  $("#inspector").querySelectorAll("[data-header-key]").forEach(el=>{el.oninput=()=>{p.header??={};p.header[el.dataset.headerKey]=el.checked;markDirty();renderCanvas()}});
  const media=$("#chooseMedia");if(media)media.onclick=()=>{uploadTarget=selected;$("#mediaPicker").accept=target.type==="video"?"video/*":"image/*";$("#mediaPicker").click()};
  const icon=$("#chooseIcon");if(icon)icon.onclick=()=>{uploadTarget="icon";$("#mediaPicker").accept="image/*";$("#mediaPicker").click()};
  const settings=$("#projectSettings");if(settings)settings.onclick=()=>{selected=null;renderAll(false)};
  $("#inspector").querySelectorAll("[data-action]").forEach(el=>el.onclick=()=>blockAction(el.dataset.action));
}
function moveCategory(index,direction){const target=index+direction;if(target<0||target>=data.categories.length)return;[data.categories[index],data.categories[target]]=[data.categories[target],data.categories[index]];markDirty();renderAll()}
function deleteCategory(index){if(data.categories.length===1)return alert("You need at least one category.");const removed=data.categories[index];if(!confirm(`Remove "${removed}"? Projects in it will move to "${data.categories[index===0?1:0]}".`))return;data.categories.splice(index,1);const replacement=data.categories[0];data.projects.forEach(item=>{if(item.category===removed)item.category=replacement});markDirty();renderAll()}
function blockAction(action){const a=project().blocks,i=selected;if(action==="delete"){a.splice(i,1);selected=null}else if(action==="duplicate"){a.splice(i+1,0,structuredClone(a[i]));selected=i+1}else if(action==="up"&&i>0){[a[i-1],a[i]]=[a[i],a[i-1]];selected--}else if(action==="down"&&i<a.length-1){[a[i+1],a[i]]=[a[i],a[i+1]];selected++}markDirty();renderAll(false)}
function renderProjects(){
  $("#projectList").innerHTML=data.projects.map((p,i)=>`<button class="project-row ${i===projectIndex&&selected!=="categories"?"active":""}" data-project="${i}">${esc(p.title)}<span>${esc(p.category)}</span></button>`).join("")+`<button class="manage-categories ${selected==="categories"?"active":""}" id="manageCategories">Manage categories</button>`;
  $("#projectList").querySelectorAll("[data-project]").forEach(el=>el.onclick=()=>{projectIndex=+el.dataset.project;selected=null;insertAt=null;renderAll()});
  $("#manageCategories").onclick=()=>{selected="categories";insertAt=null;renderAll()};
}
function renderAll(list=true){if(list)renderProjects();renderCanvas();renderInspector()}
$("#mediaPicker").onchange=async e=>{const file=e.target.files[0];if(!file)return;const p=project();$("#status").textContent="Uploading media…";const res=await fetch(`/api/upload?slug=${encodeURIComponent(p.slug)}&name=${encodeURIComponent(file.name)}`,{method:"POST",body:file});const result=await res.json();if(uploadTarget==="icon")p.image=result.path;else p.blocks[uploadTarget].src=result.path;markDirty();e.target.value="";renderAll(false)};
$("#save").onclick=async()=>{const button=$("#save");button.disabled=true;button.textContent="Saving…";const res=await fetch("/api/content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});button.disabled=false;button.textContent="Save changes";if(res.ok){dirty=false;$("#status").textContent="Saved";$("#status").className=""}else $("#status").textContent="Save failed"};
$("#newProject").onclick=()=>{const title=prompt("Project name");if(!title)return;const slug=title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");data.projects.push({title,displayTitle:title,slug,category:"Software",year:new Date().getFullYear().toString(),image:"",summary:"Add a short summary.",description:"",technologies:[],visual:"",featured:false,blocks:[]});projectIndex=data.projects.length-1;selected=null;markDirty();renderAll()};
window.addEventListener("beforeunload",e=>{if(dirty){e.preventDefault();e.returnValue=""}});
fetch("/api/content").then(r=>r.json()).then(value=>{data=value;data.projects.forEach(p=>p.blocks??=[]);$("#loading").hidden=true;$("#app").hidden=false;renderAll()}).catch(e=>$("#loading").textContent=`Could not open content: ${e.message}`);
